### ISSUE TITLE
Lava Sigil Dupe

### ISSUE THREAD

**Issue by Bagabundoman** [EnderExtreme/Toxic-Garbage-Island#12]
Issue information in sevtech concerning using a lava sigil on any fluid tank https://github.com/Darkosto/SevTech-Ages/issues/2059

According to the Sevtech issue page, the issue is already fixed in a future Blood Magic version.

**Comment by Rongmario** [comment]
https://github.com/WayofTime/BloodMagic/commit/77bdbed8b5646dd361fd44541bbef47a0f982732 Implemented and mod released!

Also, seems like Buildcraft tanks + Tinker's tanks duped only. Anyways, BC may go - unsure yet; at least it's fixed though.
