### ISSUE TITLE
Lava Crystal Gets Consumed by IE Alloy Kiln

### ISSUE THREAD

**Issue by Bagabundoman** [EnderExtreme/Toxic-Garbage-Island#13]
Issue information in sevtech/blood magic - "if you place a lava crystal inside the alloy kiln as a fuel source, the alloy kiln eats the lava crystal instead of behaving like the lava crystal should and draining lp" https://github.com/Darkosto/SevTech-Ages/issues/2033

**Comment by Rongmario** [comment]
Fixed in Mekanism, not sure about Alloy Kiln.
