### ISSUE TITLE
IE Conveyor Belts & Probably Game Stages Conflict

### ISSUE THREAD

**Issue by Bagabundoman** [EnderExtreme/Toxic-Garbage-Island#14]
Issue information in sevtech/Immersive Engineering, also seems like it's related to game stages? https://github.com/Darkosto/SevTech-Ages/issues/1999

Despite supposedly having the necessary things unlocked for conveyor belts, user is spammed with messages when trying to rotate a conveyor belt with an IE hammer.

It's entirely possible this bug is a result of sevtech's specific configs of stages/unlockables.

**Comment by Rongmario** [comment]
I'll reopen if I face this.
