### ISSUE TITLE
AE2 P2P Tunnels Don't Connect to Mekanism Cables

### ISSUE THREAD

**Issue by Bagabundoman** [EnderExtreme/Toxic-Garbage-Island#15]
Issue information in sevtech/AE2/Mekanism - https://github.com/Darkosto/SevTech-Ages/issues/1973

Has the status "reported to mod" for sevtech, nothing much to do about it.

**Comment by Rongmario** [comment]
Mekanism cables are bugged so much. :/

**Comment by Rongmario** [comment]
Works as of this commit! https://github.com/aidancbrady/Mekanism/commit/11df807002ddf3021b666587239f47dc87449bf2
