### ISSUE TITLE
IE Assembler/Probably Any Auto-crafter Bypassing Currently Unknown Recipes

### ISSUE THREAD

**Issue by Bagabundoman** [EnderExtreme/Toxic-Garbage-Island#18]
Issue information in sevtech/Game Stages- https://github.com/Darkosto/SevTech-Ages/issues/1803

Something to think about when designing progression...

**Comment by Rongmario** [comment]
I'll see what I can about autocrafting solutions, seems bizarre GameStages doesn't follow FakePlayer progression too (like Reskillable does).

**Comment by Rongmario** [comment]
Fixed.
