### ISSUE TITLE
Bibliocraft Printing Press Doesn't Work

### ISSUE THREAD

**Issue by Bagabundoman** [EnderExtreme/Toxic-Garbage-Island#19]
Issue information in sevtech/bibliocraft- https://github.com/Darkosto/SevTech-Ages/issues/1429

Sounds like it's just straight up br0ke, sevtech or not. Supposedly, it has been reported to mod author.

**Comment by Rongmario** [comment]
BC author won't be around a lot, he always goes after updating his mod to a major version :/

I'll be disabling this feature anyways, don't want enchantment duplication to happen this way :)
