### ISSUE TITLE
Add Will Smith Saying "Aw That's Hot, That's Hot" Sound Effect When Temperature Increases

### ISSUE THREAD

**Issue by Bagabundoman** [EnderExtreme/Toxic-Garbage-Island#196]
https://www.youtube.com/watch?v=l5forhriVhY

Would serve as a warning to players when temperature starts to dramatically/dangerously increase (otherwise I bet you they'll forget at least the first few times).

Also, memes.

**Comment by Bagabundoman** [comment]
Also I propose 6:27 to 6:30 of this video as a coldness warning to make it a really proper shitpost https://youtu.be/ZCMZaWFq4Vw?t=387

**Comment by Rongmario** [comment]
Done!
