### ISSUE TITLE
Astral Sorcery JEI Recipes Gone After Progression

### ISSUE THREAD

**Issue by Bagabundoman** [EnderExtreme/Toxic-Garbage-Island#20]
Issue information in sevtech/Astral sorcery/jei- https://github.com/Darkosto/SevTech-Ages/issues/1323

Might be entirely dependent on whatever sevtech did to mess with astral's recipes.

**Comment by Rongmario** [comment]
Seems to be related to OptiFine. Which for all who sees this, please use BetterFPS if you need.

**Comment by Rongmario** [comment]
I'll update if Optifine or Astral does get updated.
