### ISSUE TITLE
Immersive Tech Boiler Crash

### ISSUE THREAD

**Issue by Bagabundoman** [EnderExtreme/Toxic-Garbage-Island#21]
Issue information in sevtech/immersive tech - https://github.com/Darkosto/SevTech-Ages/issues/1250

Not explained well at all, but towards the bottom of the comments it sounds like a fix for the mod is either on the way or already released, just have to use the most updated version ¯\_(ツ)_/¯

**Comment by Rongmario** [comment]
We won't be needing this mod anymore. The author has half-implemented stuff in releases, fucks me up. Also, several other crashes have been spotted, we will be using distillery from IC2 + more if we REALLY need processes such as this.
