### ISSUE TITLE
Damascus Steel, to keep or no

### ISSUE THREAD

**Issue by Rongmario** [EnderExtreme/Toxic-Garbage-Island#230]

**Comment by leagris** [comment]
While in reality: [Damascus Steel](https://en.wikipedia.org/wiki/Damascus_steel) refers to a geographical region/town Damas, and historical smithing process art; It is nice to have as a bonus loot special material.

I always witnessed that Gregtech or its successors forks would include Player own progressive skills.
Some processing knowledges could be unlocked with advancements.
It could have Damascus Steel exclusively and manually craftable by skilled players, having unlocked the recipe by reaching the proper advancement, and possibly consuming XP in the process.

**Comment by Rongmario** [comment]
I am planning for a pretty basic advancement system in GT, but for the modpack, I will possibly use GameStages or Reskillable to handle something like what you have said.

**Comment by Rongmario** [comment]
I'll keep it, but nothing substantial will come out of it as of now.
