### ISSUE TITLE
Change Geiger Counter GUI location

### ISSUE THREAD

**Issue by Rongmario** [EnderExtreme/Toxic-Garbage-Island#241]
https://www.reddit.com/r/feedthebeast/comments/bm1wur/what_mod_adds_the_0_radst_how_do_i_remove_it_it/

**Comment by Rongmario** [comment]
Changed. Now looks like: 
![image](https://user-images.githubusercontent.com/3684700/57520493-b59d4080-7315-11e9-9fc8-72db3c5ec049.png)

**Comment by borner112** [comment]
> Geändert. Jetzt sieht es so aus:
> ![Bild](https://user-images.githubusercontent.com/3684700/57520493-b59d4080-7315-11e9-9fc8-72db3c5ec049.png)

can u show me the nuclearcraft.cfg ? (my english is too bad 4 transfer in german this https://www.reddit.com/r/feedthebeast/comments/bm1wur/what_mod_adds_the_0_radst_how_do_i_remove_it_it/ )


![help me please  (radiation_hud_position cartesian](https://user-images.githubusercontent.com/64110171/79924935-6b837100-8439-11ea-9b73-5ae6030b56f8.PNG)

**Comment by Rongmario** [comment]
Something like this:

![image](https://user-images.githubusercontent.com/3684700/79968359-e2475b00-8487-11ea-88c4-388153e51588.png)

**Comment by Rongmario** [comment]
`
    # Optional config to specify where the rads overlay should appear on the screen if not wanted on a side or at a corner - if used, this config will be used in place of the angle-based one. Two doubles are required [x, y] which specify how far right (x) and how far down (y) from the top-left corner of the screen the overlay is drawn at.
    D:radiation_hud_position_cartesian <
        0.005
        0.892
     >

`

**Comment by borner112** [comment]
thank you.  its works
