### ISSUE TITLE
terrible suggestion

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [EnderExtreme/Toxic-Garbage-Island#258]
Change the "you may not rest now, there are monsters nearby" message to some weird shit, some good ones are:
You may not rest now, you haven't beat your meat for the 7th time and it's almost 3 am
You may not rest now,you have your existential dread to deal with.
You may not rest now,there are hot singles near your area.
Kill the monsters around you first, retard.

**Comment by PoptartOverlord-Xabedo** [comment]
Moreover, how about changing "you can only sleep at night" message to something else, like:

No, you can't have your "five more minutes"
Going back to bed eh? 

I bet your laziness has negatively affected you and you live a miserable life  full of regrets.


oh you're finally awake? You were trying to cross that border, eh?.......(the whole copypasta)

**Comment by Rongmario** [comment]
I forgot this was retarded
