### ISSUE TITLE
[EXPERIMENTAL] Cubic Chunks Integration

### ISSUE THREAD

**Issue by Rongmario** [EnderExtreme/Toxic-Garbage-Island#29]
I'll log all the difficulty we have if we integrate with CC right now. I will work closely with Archengius and Barteks with this. This is very experimental and hence I will create another instance and will only dive deeper if I think its necessary and worth it.

1. Worldgen heavily will rely on GregTech, as it hooks into CC fully. Planned soon(tm)
2. Applied Energistics spatial dimension crashes upon worldgen [URGENT]:: https://github.com/OpenCubicChunks/CubicChunks/issues/374 (Turned off Spatial Dimension works...)
3. Twilight Forest taking long time to prepare when going through portal [URGENT]: https://github.com/OpenCubicChunks/CubicChunks/issues/355 (Turning off Cubic ability here)
4. Dynamic Surroundings: https://github.com/OpenCubicChunks/CubicChunks/issues/375
5. ForgeMultipart: https://gist.github.com/Rongmario/c3f62aa6ed0d3f7f5171f0873ce212f4 (NOW WORKS BUT MAY NEED TO DISABLE OBTAINING OF MULTIPART BLOCKS)

**Comment by Rongmario** [comment]
New issue: https://github.com/OpenCubicChunks/CubicChunks/issues/375

**Comment by Rongmario** [comment]
New CodeChickenMods (ForgeMultipart only?) issue... :
https://gist.github.com/Rongmario/c3f62aa6ed0d3f7f5171f0873ce212f4

**Comment by Rongmario** [comment]
Astral Sorcery is working with latest build o.o

**Comment by Rongmario** [comment]
Thaumcraft works too! Pech issue is also fixed!

**Comment by Rongmario** [comment]
Deep Dark freezes on loading in.

**Comment by Rongmario** [comment]
Dimensional Doors won't work right now:

`Caused by: java.lang.IllegalArgumentException: Cube at 0 already exists!
	at cubicchunks.world.column.CubeMap.put(CubeMap.java:72)
	at net.minecraft.world.chunk.Chunk.addCube(Chunk.java:3741)
	at cubicchunks.server.CubeProviderServer.onCubeLoaded(CubeProviderServer.java:339)
	at cubicchunks.server.CubeProviderServer.generateCube(CubeProviderServer.java:412)
	at cubicchunks.server.CubeProviderServer.postCubeLoadAttempt(CubeProviderServer.java:374)
	at cubicchunks.server.CubeProviderServer.getCube(CubeProviderServer.java:322)
	at cubicchunks.server.CubeProviderServer.getCube(CubeProviderServer.java:251)
	at net.minecraft.world.chunk.Chunk.getEBS_CubicChunks(Chunk.java:1745)
	at net.minecraft.world.chunk.Chunk.func_186032_a(Chunk.java:1982)
	... 19 more

[21:03:38] [Server thread/ERROR] [cubicchunks]: Attempting to unload already unloaded cube at CubePos(30, 0, 2)`

**Comment by Rongmario** [comment]
I'm going to update more here: https://github.com/OpenCubicChunks/CubicChunks/wiki/Mod-Compatibility-for-Minecraft-1.12.2-(Pre-API)

**Comment by TheDeviantCrafter** [comment]
As a temporary workaround, you can use Chunk Pregenerator to pregenerate the Twilight Forest dimension.

**Comment by Rongmario** [comment]
@TheDeviantCrafter I have not tried Chunk Pregenerator with Cubic Chunks, I'm not sure if it would work.

**Comment by Rongmario** [comment]
Full log + first crash: https://paste.ee/p/usPNq

2nd crash: https://hastebin.com/udiwuvebuv.sql (Happened after reloading the world with the multipart placed gone, then still crashed by walking onto the removed or invisible multipart)

3rd crash: https://paste.dimdev.org/ayigawotaq.txt (I know this happened on drawing outlines of the multipart when placing)

Dropping it here for future reference, as am not sure what is clearly causing it (fmp or cc side)

**Comment by Rongmario** [comment]
Main post updated! Many issues eliminated, no new issues popping up at this moment.

**Comment by Rongmario** [comment]
Re-opening in future, lots of lag, and fixes needed. Sigh.
