### ISSUE TITLE
Disable obsidian making in overworld

### ISSUE THREAD

**Issue by Rongmario** [EnderExtreme/Toxic-Garbage-Island#69]

**Comment by Rongmario** [comment]
Only allowed Twilight Forest + Betweenlands dims to be able to make obsidian. Right now, in other dimensions it'll just transform into cobblestone; open to suggestion of what it could become.

**Comment by Rongmario** [comment]
Decided against. You'll only be able to find portals occur naturally.

**Comment by Waisse** [comment]
So no in-world obsidian formation at all ? In all dimensions ?

**Comment by Rongmario** [comment]
Custom structures will, or if you count the End there's quite a bit there.

**Comment by Rongmario** [comment]
By the previous statement above yours I meant you can make obsidian in world traditionally but you can't light portals.
