### ISSUE TITLE
Actually Additions Changes

### ISSUE THREAD

**Issue by Rongmario** [EnderExtreme/Toxic-Garbage-Island#8]
## Disabled:
1. All tools + AIOTs
2. Item Repairer
3. Lush Caves
4. Treasure Chests

**Comment by Rongmario** [comment]
Decided to cut this out from the pack, OP aspects + useless shit.

**Comment by Rongmario** [comment]
Needs review however.

**Comment by Rongmario** [comment]
Totally removal. Too OP, duplicated mechanisms with other mods.

**Comment by Waisse** [comment]
I like empowered oil automation tho

**Comment by Rongmario** [comment]
Try do something similar with GT, it'll be more fun :^)
