### ISSUE TITLE
Give Phyto-Gro Uses

### ISSUE THREAD

**Issue by Rongmario** [EnderExtreme/Toxic-Garbage-Island#80]
Since we have no Thermal Expansion installed.

**Comment by Waisse** [comment]
It already has uses, it's an AOE bonemeal : normal is 3X3, rich is 5X5 and fluxed is 7X7.
Could oredict/replace bonemeal in relevant recipes maybe ?

**Comment by Rongmario** [comment]
Yeah, I want to give it some uses on botanical side of things. Maybe something to do with extreme growth.

**Comment by Rongmario** [comment]
Lamp of Growth now requires Fluxed Phyto-Gro!

**Comment by Rongmario** [comment]
Done!
