### ISSUE TITLE
Icons needed for skills+unlockables

### ISSUE THREAD

**Issue by Rongmario** [EnderExtreme/Toxic-Garbage-Island#91]
- [x] Excavation
- [x] Axes
- [x] Fishing
- [x] Smelting
- [x] Attack Symbol
- [x] Resistence (Defense) Symbol

**Comment by Bagabundoman** [comment]
![attack badge](https://user-images.githubusercontent.com/38775134/47595166-d9d29a80-d94c-11e8-8479-22c92e3b8c85.png) Attack
![attack](https://user-images.githubusercontent.com/38775134/47595167-d9d29a80-d94c-11e8-8578-19ffc8013edd.png)
![defense badge](https://user-images.githubusercontent.com/38775134/47595168-d9d29a80-d94c-11e8-80ef-6dc593e3e082.png) Resistance/Defense
![defense](https://user-images.githubusercontent.com/38775134/47595169-da6b3100-d94c-11e8-8e46-bcd5834c911b.png)
![smelting badge](https://user-images.githubusercontent.com/38775134/47595170-da6b3100-d94c-11e8-97bf-e34ecadb756c.png) Smelting
![smelting](https://user-images.githubusercontent.com/38775134/47595171-da6b3100-d94c-11e8-9cde-a805a0f544e2.png)

**Comment by Rongmario** [comment]
Much love
